version: "2"

run:
  build-tags:
    - integration
    - unit

  timeout: 5m
  tests: true

linters:
  settings:
    varnamelen:
      ignore-names:
        - ok
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
  default: all
  disable:
    - depguard
    - wsl
    - nolintlint

  exclusions:
    generated: strict
    warn-unused: false
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - noinlineerr

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: strict
