// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/service (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_repository.go -package=mocks github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/service Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetDailyActivityByProject mocks base method.
func (m *MockRepository) GetDailyActivityByProject(ctx context.Context, projectID int) ([]repository.DailyActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyActivityByProject", ctx, projectID)
	ret0, _ := ret[0].([]repository.DailyActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyActivityByProject indicates an expected call of GetDailyActivityByProject.
func (mr *MockRepositoryMockRecorder) GetDailyActivityByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyActivityByProject", reflect.TypeOf((*MockRepository)(nil).GetDailyActivityByProject), ctx, projectID)
}

// GetIssuesDurationByProject mocks base method.
func (m *MockRepository) GetIssuesDurationByProject(ctx context.Context, projectID int) ([]repository.IssueDuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuesDurationByProject", ctx, projectID)
	ret0, _ := ret[0].([]repository.IssueDuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuesDurationByProject indicates an expected call of GetIssuesDurationByProject.
func (mr *MockRepositoryMockRecorder) GetIssuesDurationByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuesDurationByProject", reflect.TypeOf((*MockRepository)(nil).GetIssuesDurationByProject), ctx, projectID)
}

// GetIssuesTimeSpentByProject mocks base method.
func (m *MockRepository) GetIssuesTimeSpentByProject(ctx context.Context, projectID int) ([]repository.IssueTimeSpent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuesTimeSpentByProject", ctx, projectID)
	ret0, _ := ret[0].([]repository.IssueTimeSpent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuesTimeSpentByProject indicates an expected call of GetIssuesTimeSpentByProject.
func (mr *MockRepositoryMockRecorder) GetIssuesTimeSpentByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuesTimeSpentByProject", reflect.TypeOf((*MockRepository)(nil).GetIssuesTimeSpentByProject), ctx, projectID)
}

// GetPriorityStatsByProject mocks base method.
func (m *MockRepository) GetPriorityStatsByProject(ctx context.Context, projectID int) ([]repository.PriorityStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityStatsByProject", ctx, projectID)
	ret0, _ := ret[0].([]repository.PriorityStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityStatsByProject indicates an expected call of GetPriorityStatsByProject.
func (mr *MockRepositoryMockRecorder) GetPriorityStatsByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityStatsByProject", reflect.TypeOf((*MockRepository)(nil).GetPriorityStatsByProject), ctx, projectID)
}

// GetProjectLastUpdated mocks base method.
func (m *MockRepository) GetProjectLastUpdated(ctx context.Context, projectID int) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectLastUpdated", ctx, projectID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectLastUpdated indicates an expected call of GetProjectLastUpdated.
func (mr *MockRepositoryMockRecorder) GetProjectLastUpdated(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectLastUpdated", reflect.TypeOf((*MockRepository)(nil).GetProjectLastUpdated), ctx, projectID)
}

// GetStatsByProject mocks base method.
func (m *MockRepository) GetStatsByProject(ctx context.Context, projectID int) (repository.ProjectStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByProject", ctx, projectID)
	ret0, _ := ret[0].(repository.ProjectStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByProject indicates an expected call of GetStatsByProject.
func (mr *MockRepositoryMockRecorder) GetStatsByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByProject", reflect.TypeOf((*MockRepository)(nil).GetStatsByProject), ctx, projectID)
}

// GetStatusTransitionsByProject mocks base method.
func (m *MockRepository) GetStatusTransitionsByProject(ctx context.Context, projectID int) ([]repository.StatusTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusTransitionsByProject", ctx, projectID)
	ret0, _ := ret[0].([]repository.StatusTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusTransitionsByProject indicates an expected call of GetStatusTransitionsByProject.
func (mr *MockRepositoryMockRecorder) GetStatusTransitionsByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusTransitionsByProject", reflect.TypeOf((*MockRepository)(nil).GetStatusTransitionsByProject), ctx, projectID)
}
