// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/service (interfaces: Cache)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_cache.go -package=mocks github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/service Cache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCache) Get(ctx context.Context, projectID int, dataType string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, projectID, dataType)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(ctx, projectID, dataType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), ctx, projectID, dataType)
}

// GetLastUpdated mocks base method.
func (m *MockCache) GetLastUpdated(ctx context.Context, projectID int) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdated", ctx, projectID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdated indicates an expected call of GetLastUpdated.
func (mr *MockCacheMockRecorder) GetLastUpdated(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdated", reflect.TypeOf((*MockCache)(nil).GetLastUpdated), ctx, projectID)
}

// Invalidate mocks base method.
func (m *MockCache) Invalidate(ctx context.Context, projectID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockCacheMockRecorder) Invalidate(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockCache)(nil).Invalidate), ctx, projectID)
}

// Set mocks base method.
func (m *MockCache) Set(ctx context.Context, projectID int, dataType string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, projectID, dataType, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(ctx, projectID, dataType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), ctx, projectID, dataType, value)
}

// SetLastUpdated mocks base method.
func (m *MockCache) SetLastUpdated(ctx context.Context, projectID int, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastUpdated", ctx, projectID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastUpdated indicates an expected call of SetLastUpdated.
func (mr *MockCacheMockRecorder) SetLastUpdated(ctx, projectID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastUpdated", reflect.TypeOf((*MockCache)(nil).SetLastUpdated), ctx, projectID, t)
}
