// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/handler/grpc (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/handler/grpc Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/Go-Yadro-Group-1/Jira-Analyzer/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetChart mocks base method.
func (m *MockService) GetChart(ctx context.Context, projectID int, chartType service.ChartType) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChart", ctx, projectID, chartType)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChart indicates an expected call of GetChart.
func (mr *MockServiceMockRecorder) GetChart(ctx, projectID, chartType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChart", reflect.TypeOf((*MockService)(nil).GetChart), ctx, projectID, chartType)
}

// GetProjectStat mocks base method.
func (m *MockService) GetProjectStat(ctx context.Context, projectID int) (service.ProjectStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectStat", ctx, projectID)
	ret0, _ := ret[0].(service.ProjectStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectStat indicates an expected call of GetProjectStat.
func (mr *MockServiceMockRecorder) GetProjectStat(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectStat", reflect.TypeOf((*MockService)(nil).GetProjectStat), ctx, projectID)
}

// ListProjects mocks base method.
func (m *MockService) ListProjects(ctx context.Context) ([]service.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx)
	ret0, _ := ret[0].([]service.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockServiceMockRecorder) ListProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockService)(nil).ListProjects), ctx)
}

// DeleteProject mocks base method.
func (m *MockService) DeleteProject(ctx context.Context, projectID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockServiceMockRecorder) DeleteProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockService)(nil).DeleteProject), ctx, projectID)
}
